# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86_64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86_64)
  HydrogenEngine_config = debug_x86_64
  HydrogenEditor_config = debug_x86_64
  HydrogenRuntime_config = debug_x86_64

else ifeq ($(config),debug_arm64)
  HydrogenEngine_config = debug_arm64
  HydrogenEditor_config = debug_arm64
  HydrogenRuntime_config = debug_arm64

else ifeq ($(config),release_x86_64)
  HydrogenEngine_config = release_x86_64
  HydrogenEditor_config = release_x86_64
  HydrogenRuntime_config = release_x86_64

else ifeq ($(config),release_arm64)
  HydrogenEngine_config = release_arm64
  HydrogenEditor_config = release_arm64
  HydrogenRuntime_config = release_arm64

else ifeq ($(config),dist_x86_64)
  HydrogenEngine_config = dist_x86_64
  HydrogenEditor_config = dist_x86_64
  HydrogenRuntime_config = dist_x86_64

else ifeq ($(config),dist_arm64)
  HydrogenEngine_config = dist_arm64
  HydrogenEditor_config = dist_arm64
  HydrogenRuntime_config = dist_arm64

else ifeq ($(config),debug-noimgui_x86_64)
  HydrogenEngine_config = debug-noimgui_x86_64
  HydrogenEditor_config = debug-noimgui_x86_64
  HydrogenRuntime_config = debug-noimgui_x86_64

else ifeq ($(config),debug-noimgui_arm64)
  HydrogenEngine_config = debug-noimgui_arm64
  HydrogenEditor_config = debug-noimgui_arm64
  HydrogenRuntime_config = debug-noimgui_arm64

else ifeq ($(config),release-noimgui_x86_64)
  HydrogenEngine_config = release-noimgui_x86_64
  HydrogenEditor_config = release-noimgui_x86_64
  HydrogenRuntime_config = release-noimgui_x86_64

else ifeq ($(config),release-noimgui_arm64)
  HydrogenEngine_config = release-noimgui_arm64
  HydrogenEditor_config = release-noimgui_arm64
  HydrogenRuntime_config = release-noimgui_arm64

else ifeq ($(config),dist-noimgui_x86_64)
  HydrogenEngine_config = dist-noimgui_x86_64
  HydrogenEditor_config = dist-noimgui_x86_64
  HydrogenRuntime_config = dist-noimgui_x86_64

else ifeq ($(config),dist-noimgui_arm64)
  HydrogenEngine_config = dist-noimgui_arm64
  HydrogenEditor_config = dist-noimgui_arm64
  HydrogenRuntime_config = dist-noimgui_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := HydrogenEngine HydrogenEditor HydrogenRuntime

.PHONY: all clean help $(PROJECTS) Engine

all: $(PROJECTS)

Engine: HydrogenEditor HydrogenEngine HydrogenRuntime

HydrogenEngine:
ifneq (,$(HydrogenEngine_config))
	@echo "==== Building HydrogenEngine ($(HydrogenEngine_config)) ===="
	@${MAKE} --no-print-directory -C HydrogenEngine -f Makefile config=$(HydrogenEngine_config)
endif

HydrogenEditor: HydrogenEngine
ifneq (,$(HydrogenEditor_config))
	@echo "==== Building HydrogenEditor ($(HydrogenEditor_config)) ===="
	@${MAKE} --no-print-directory -C HydrogenEditor -f Makefile config=$(HydrogenEditor_config)
endif

HydrogenRuntime: HydrogenEngine
ifneq (,$(HydrogenRuntime_config))
	@echo "==== Building HydrogenRuntime ($(HydrogenRuntime_config)) ===="
	@${MAKE} --no-print-directory -C HydrogenRuntime -f Makefile config=$(HydrogenRuntime_config)
endif

clean:
	@${MAKE} --no-print-directory -C HydrogenEngine -f Makefile clean
	@${MAKE} --no-print-directory -C HydrogenEditor -f Makefile clean
	@${MAKE} --no-print-directory -C HydrogenRuntime -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86_64"
	@echo "  debug_arm64"
	@echo "  release_x86_64"
	@echo "  release_arm64"
	@echo "  dist_x86_64"
	@echo "  dist_arm64"
	@echo "  debug-noimgui_x86_64"
	@echo "  debug-noimgui_arm64"
	@echo "  release-noimgui_x86_64"
	@echo "  release-noimgui_arm64"
	@echo "  dist-noimgui_x86_64"
	@echo "  dist-noimgui_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   HydrogenEngine"
	@echo "   HydrogenEditor"
	@echo "   HydrogenRuntime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"